# Copyright 2017, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [START app_yaml]
#env: flex
runtime: python27
threadsafe: true
handlers:
  - url: /static/js/(.*)
    static_files: build/static/js/\1
    upload: build/static/js/(.*)

  - url: /assets/css/(.*)
    static_files: build/assets/css/\1
    upload: build/assets/css/(.*)
  - url: /assets/css/plugins/(.*)
    static_files: build/assets/css/plugins/\1
    upload: build/assets/css/plugins/(.*)  

  - url: /assets/images/(.*)
    static_files: build/assets/images/\1
    upload: build/assets/images/(.*)

  - url: /assets/js/(.*)
    static_files: build/assets/js/\1
    upload: build/assets/js/(.*)  
  - url: /assets/js/plugins/(.*)
    static_files: build/assets/js/plugins/\1
    upload: build/assets/js/plugins/(.*)    

  - url: /assets/revolution/(.*)
    static_files: build/assets/revolution/\1
    upload: build/assets/revolution/(.*) 
  - url: /assets/revolution/assets/(.*)
    static_files: build/assets/revolution/assets/\1
    upload: build/assets/revolution/assets/(.*)
  - url: /assets/revolution/css/(.*)
    static_files: build/assets/revolution/css/\1
    upload: build/assets/revolution/css/(.*) 
  - url: /assets/revolution/fonts/(.*)
    static_files: build/assets/revolution/fonts/\1
    upload: build/assets/revolution/fonts/(.*)  
  - url: /assets/revolution/js/(.*)
    static_files: build/assets/revolution/js/\1
    upload: build/assets/revolution/js/(.*)         

  - url: /assets/scsss/(.*)
    static_files: build/assets/scss/\1
    upload: build/assets/scss/(.*)   

  - url: /assets/ionicons/css/(.*)
    static_files: build/assets/ionicons/css/\1
    upload: build/assets/ionicons/css/(.*)    
  - url: /assets/ionicons/fonts/(.*)
    static_files: build/assets/ionicons/fonts/\1
    upload: build/assets/ionicons/fonts/(.*)   

  - url: /assets/lightbox-2/css/(.*)
    static_files: build/assets/lightbox-2/css/\1
    upload: build/assets/lightbox-2/css/(.*)  
  - url: /assets/lightbox-2/js/(.*)
    static_files: build/assets/lightbox-2/js/\1
    upload: build/assets/lightbox-2/js/(.*)
  - url: /assets/lightbox-2/images/(.*)
    static_files: build/assets/lightbox-2/images/\1
    upload: build/assets/lightbox-2/images/(.*)        


  - url: /assets/plugins/aos/(.*)
    static_files: build/assets/plugins/aos/\1
    upload: build/assets/plugins/aos/(.*)  
  - url: /assets/plugins/bootstrap/(.*)
    static_files: build/assets/plugins/bootstrap/\1
    upload: build/assets/plugins/bootstrap/(.*)
  - url: /assets/plugins/flexslider/(.*)
    static_files: build/assets/plugins/flexslider/\1
    upload: build/assets/plugins/flexslider/(.*)
  - url: /assets/plugins/jquery/(.*)
    static_files: build/assets/plugins/jquery/\1
    upload: build/assets/plugins/jquery/(.*)
  - url: /assets/plugins/masonry/(.*)
    static_files: build/assets/plugins/masonry/\1
    upload: build/assets/plugins/masonry/(.*)
  - url: /assets/plugins/pushy/(.*)
    static_files: build/assets/plugins/pushy/\1
    upload: build/assets/plugins/pushy/(.*)                  

  - url: /(.*\.(json|ico))$
    static_files: build/\1
    upload: build/.*\.(json|ico)$
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
# [END app_yaml]